package com.foxconn.lamp.device.domain;

import java.io.Serializable;
import java.util.Date;

public class LampInfo implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = -7529819844158025355L;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lamp_info.id
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lamp_info.name
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	private String name;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lamp_info.serial
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	private String serial;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lamp_info.machine_num
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	private String machineNum;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lamp_info.maintainer
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	private String maintainer;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lamp_info.type
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	private String type;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lamp_info.status
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	private Long status;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lamp_info.desc
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	private String desc;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lamp_info.creater
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	private String creater;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lamp_info.modifier
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	private String modifier;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lamp_info.modify_time
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	private Date modifyTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lamp_info.create_time
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lamp_info.id
	 *
	 * @return the value of lamp_info.id
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	public Integer getId()
	{
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lamp_info.id
	 *
	 * @param id
	 *            the value for lamp_info.id
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	public void setId(Integer id)
	{
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lamp_info.name
	 *
	 * @return the value of lamp_info.name
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lamp_info.name
	 *
	 * @param name
	 *            the value for lamp_info.name
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	public void setName(String name)
	{
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lamp_info.serial
	 *
	 * @return the value of lamp_info.serial
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	public String getSerial()
	{
		return serial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lamp_info.serial
	 *
	 * @param serial
	 *            the value for lamp_info.serial
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	public void setSerial(String serial)
	{
		this.serial = serial == null ? null : serial.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lamp_info.machine_num
	 *
	 * @return the value of lamp_info.machine_num
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	public String getMachineNum()
	{
		return machineNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lamp_info.machine_num
	 *
	 * @param machineNum
	 *            the value for lamp_info.machine_num
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	public void setMachineNum(String machineNum)
	{
		this.machineNum = machineNum == null ? null : machineNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lamp_info.maintainer
	 *
	 * @return the value of lamp_info.maintainer
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	public String getMaintainer()
	{
		return maintainer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lamp_info.maintainer
	 *
	 * @param maintainer
	 *            the value for lamp_info.maintainer
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	public void setMaintainer(String maintainer)
	{
		this.maintainer = maintainer == null ? null : maintainer.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lamp_info.type
	 *
	 * @return the value of lamp_info.type
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	public String getType()
	{
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lamp_info.type
	 *
	 * @param type
	 *            the value for lamp_info.type
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	public void setType(String type)
	{
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lamp_info.status
	 *
	 * @return the value of lamp_info.status
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	public Long getStatus()
	{
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lamp_info.status
	 *
	 * @param status
	 *            the value for lamp_info.status
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	public void setStatus(Long status)
	{
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lamp_info.desc
	 *
	 * @return the value of lamp_info.desc
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	public String getDesc()
	{
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lamp_info.desc
	 *
	 * @param desc
	 *            the value for lamp_info.desc
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	public void setDesc(String desc)
	{
		this.desc = desc == null ? null : desc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lamp_info.creater
	 *
	 * @return the value of lamp_info.creater
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	public String getCreater()
	{
		return creater;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lamp_info.creater
	 *
	 * @param creater
	 *            the value for lamp_info.creater
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	public void setCreater(String creater)
	{
		this.creater = creater == null ? null : creater.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lamp_info.modifier
	 *
	 * @return the value of lamp_info.modifier
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	public String getModifier()
	{
		return modifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lamp_info.modifier
	 *
	 * @param modifier
	 *            the value for lamp_info.modifier
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	public void setModifier(String modifier)
	{
		this.modifier = modifier == null ? null : modifier.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lamp_info.modify_time
	 *
	 * @return the value of lamp_info.modify_time
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	public Date getModifyTime()
	{
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lamp_info.modify_time
	 *
	 * @param modifyTime
	 *            the value for lamp_info.modify_time
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	public void setModifyTime(Date modifyTime)
	{
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lamp_info.create_time
	 *
	 * @return the value of lamp_info.create_time
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	public Date getCreateTime()
	{
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lamp_info.create_time
	 *
	 * @param createTime
	 *            the value for lamp_info.create_time
	 *
	 * @mbg.generated Thu Jul 05 17:26:55 CST 2018
	 */
	public void setCreateTime(Date createTime)
	{
		this.createTime = createTime;
	}
}