server:
  port: 8000
  servlet:
    session:
      timeout: 30
    context-path: /lamp
  tomcat:
    accesslog:
      enabled: true
      directory: d://tomcat/logs
      prefix: tomcat
      pattern: "%h %l %u %t \"%r\" [%{postdata}r] %s %{Referer}i %{User-Agent}i %T %b"
      
## master 数据源配置
master:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb?useUnicode=true&characterEncoding=utf8
    username: springbootdb
    password: springbootdb
    driverClassName: com.mysql.jdbc.Driver

## cluster 数据源配置
cluster:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb_cluster?useUnicode=true&characterEncoding=utf8
    username: springbootdb_cluster
    password: springbootdb_cluster
    driverClassName: com.mysql.jdbc.Driver
    
## mongdb 数据源配置
mongdb:
  logs:
    datasource:
      uri: localhost:27017
      database: test
      username: 
      password: 
      driverClassName:  
  pagehelper:
    helperDialect: mongdb
    offsetAsPageNum: true

##  数据源配置
lamp:
  datasource:
    url: jdbc:mysql://localhost:3306/lamp?useUnicode=true&characterEncoding=utf8
    username: lamp
    password: lamp
    driverClassName: com.mysql.jdbc.Driver

kickout: 
  forward:
    url: /loginfail
  redirect: 
    url: /login
  after:  false  
  max: 
    session: 2
  login: 
    fail: 
      redirect: 
        url: /login
      forward: 
        url: /loginfail

thirdparty: 
  dm: 
    url: https://192.168.1.10:87
  am: 
    url: https://192.168.1.10:87
  shinobi: 
    url: http://192.168.1.10:7878
    headerKe:  xxjnviGgvS
    headerAuth:  c375735f5920a7c6cc2722c5d833af3b
  starlogs: 
    url: https://192.168.1.10:87

#分页的配置
pagehelper:
  offset-as-page-num: true
  row-bounds-with-count: true
  reasonable: true
 

    
## Redis 配置
## Redis数据库索引（默认为0）
spring:
  redis:
    database:  0
## Redis服务器地址
    host: 127.0.0.1
## Redis服务器连接端口
    port: 6379
## Redis服务器连接密码（默认为空）
    password: redis
## 连接超时时间（毫秒）
    timeout: 5000
    jedis:
## 连接池最大连接数（使用负值表示没有限制）
      pool:
        max-active: 8
  ## 连接池最大阻塞等待时间（使用负值表示没有限制）
      pool.max-wait: -1
  ## 连接池中的最大空闲连接
      pool.max-idle: 8
  ## 连接池中的最小空闲连接
      pool.min-idle: 1
  #国际化
  messages:
    encoding: UTF-8
    basename: /messages/lamp-messages
    cache-duration: 300
    
    
com:
  mqtt:
    inbound:
      url: ssl://192.168.1.10:1883
      clientId: large_image_data_tricolor_lamp_camera_producer
      topics: large_image_data_tricolor_lamp_camera_revice_01
      username: Foxconn.dm.core-4a6ac9ccdd5bbe45cde3dd4e384d2253
      password: Foxconn.dm.core-4a6ac9ccdd5bbe45cde3dd4e384d2253
    outbound:
      url: ssl://192.168.1.10:1883
      clientId: large_image_data_tricolor_lamp_camera_consumer
      topic: large_image_data_tricolor_lamp_camera_revice_2
      username: Foxconn.dm.core-4a6ac9ccdd5bbe45cde3dd4e384d2253
      password: Foxconn.dm.core-4a6ac9ccdd5bbe45cde3dd4e384d2253
    task:
      corePoolSize: 5
      keepAliveSeconds: 60
      maxPoolSize: 100
      queueCapacity: 200
    camera:
      topic: large_image_data_tricolor_lamp_camera_revice_01
      qos: 2

      

    